### ISSUE TITLE
询问 License

### ISSUE THREAD

**Issue by yihong0618** [quentinck/flask4fit#1]
您好：
因为我目前在做[这个项目](https://github.com/yihong0618/running_page)

想支持佳明和佳明中国，我简单搜索了下目前GitHub上有的佳明中国的接口，发现了您的这个项目，我可能会直接借用您项目的一些代码。但是发现您的项目没有设置LICENSE，不知道可不可以，我应该不会商用。

如果不方便我可以自己实现一套，打扰您了。

**Comment by quentinck** [comment]
你好，我的代码您可以自由使用，但其中有部分代码也是引用了其他开源工程，我不太确定是否存在LICENSE问题。
另外这个代码是之前做测试使用了，后续有部分更新并没有上传，如果你在使用中存在什么问题可以与我交流。我对于FIT文件和佳明的一些数据比较擅长，看到你也比较喜欢跑步运动，有兴趣咱们可以加个微信。13507174234是我的微信号。

**Comment by yihong0618** [comment]
加您了，感谢。
